### PR TITLE
finished project

### PR DESCRIPTION
**Pull request by furiax**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@furiax does the project work ok for you? I'm getting this when running npm install: 
image

**Comment by furiax** [comment]
yes it runs fine here, had to install the npm like ng-matero with the --force command to it because they weren't updated for 17.1
Could that be the problem ?
I'm off to work now, will have a look at it this evening or tomorrow

**Comment by furiax** [comment]
Ok as far as I could find out, the error occurs cause I've installed the third party datetimepicker with the --force command. 
Since material doesn't have a datetimepicker, only a datepicker I went for a third party one. I first tried out the ngx-datetimepicker one but it gave me lots of problems to get the timespinners working, after a week of struggling I gave up and went for another one namely the ng-matero, that one I got working but it only has support up to angular 16. At first I had the same error that it wasn't compatible with angular 17 but after some research I installed it with the --force command. I know its not recommended to use --force but stackoverflow and chatgpt did suggest to do it that way.

So I tried it and it didn't gave any errors on my part. Here the application runs fine without any problem.  

What I did now in an effort to try solving it, is running an npm outdated and npm update, and he did actually update some npm's so I would say give it another try. If it still gives an error perhaps try running it with the --force command ? I don't really know what else I could do to solve it in an other way. If you would be familiar with a workaround for this type of problem, I would gladly hear it.

**Comment by TheCSharpAcademy** [comment]
@furiax Ok I'll give it a go. I love Angular but sometimes its dependencies can be a pain. 😡

**Comment by furiax** [comment]
@TheCSharpAcademy Gave it a second look today, seems like the npm's that were giving errors weren't used anymore, they were installed at my first attempt with another datetimepicker, the one I couldn't get to work. I then switched to the ng-matero one (which got an update to 17 this week by the way), so I updated the matero one to the newest version and I uninstalled the unused npm's that gave the errors. And with success.

I just gave it a quick test and got no more errors when I do the npm install and the application still works.
So please give it another try.

**Pull request merged**
